FROM python:{{ python_version }}-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE {{ docker_port }}

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "{{ docker_port }}"]