"""Generation manifest: records what was generated, used by updater to distinguish template-origin files from user-added files."""

import hashlib
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

MANIFEST_FILENAME = ".template_gen_manifest.json"


def _hash_content(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def write_manifest(
    project_dir: str,
    template_name: str,
    template_version: str,
    variables: Dict[str, Any],
    rendered_files: Dict[str, str],
) -> str:
    project_path = Path(project_dir).resolve()
    project_path.mkdir(parents=True, exist_ok=True)

    files_entry: Dict[str, str] = {}
    for rel_path, content in sorted(rendered_files.items()):
        files_entry[rel_path] = _hash_content(content)

    manifest = {
        "generated_at": datetime.now().isoformat(),
        "template_name": template_name,
        "template_version": template_version,
        "variables": variables,
        "files": files_entry,
    }

    manifest_path = project_path / MANIFEST_FILENAME
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    return str(manifest_path)


def load_manifest(project_dir: str) -> Optional[Dict[str, Any]]:
    manifest_path = Path(project_dir) / MANIFEST_FILENAME
    if not manifest_path.exists():
        return None
    with open(manifest_path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_template_files_from_manifest(project_dir: str) -> Set[str]:
    """Return the set of file paths that were generated by the template (from manifest)."""
    manifest = load_manifest(project_dir)
    if manifest is None:
        return set()
    return set(manifest.get("files", {}).keys())


def classify_project_files(
    project_dir: str,
    new_render: Dict[str, str],
) -> Dict[str, Any]:
    """
    Classify files in the project into categories for safe incremental update.
    Returns a dict with keys: unchanged, changed, template_new, template_removed, user_only.
    """
    project_path = Path(project_dir).resolve()
    manifest = load_manifest(project_dir)

    template_files: Set[str] = set()
    if manifest:
        template_files = set(manifest.get("files", {}).keys())

    existing_files: Set[str] = set()
    for root, dirs, files in os.walk(project_path):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__", ".venv", "venv", "node_modules")]
        for f in files:
            if f.endswith((".pyc", ".pyo")) or f == MANIFEST_FILENAME:
                continue
            rel = os.path.relpath(os.path.join(root, f), project_path)
            rel = rel.replace("\\", "/")
            existing_files.add(rel)

    new_file_paths = set(new_render.keys())

    unchanged: List[str] = []
    changed: List[str] = []
    template_new: List[str] = []
    template_removed: List[str] = []
    user_only: List[str] = []

    both = existing_files & new_file_paths
    for rel_path in both:
        current_path = project_path / rel_path
        if current_path.exists():
            current_content = current_path.read_text(encoding="utf-8")
        else:
            current_content = ""
        new_content = new_render[rel_path]

        if current_content == new_content:
            unchanged.append(rel_path)
        else:
            changed.append(rel_path)

    for rel_path in new_file_paths - existing_files:
        template_new.append(rel_path)

    for rel_path in existing_files - new_file_paths:
        if template_files and rel_path in template_files:
            template_removed.append(rel_path)
        else:
            user_only.append(rel_path)

    return {
        "unchanged": sorted(unchanged),
        "changed": sorted(changed),
        "template_new": sorted(template_new),
        "template_removed": sorted(template_removed),
        "user_only": sorted(user_only),
    }


def update_manifest_after_update(
    project_dir: str,
    template_name: str,
    template_version: str,
    variables: Dict[str, Any],
    new_render: Dict[str, str],
    classifications: Dict[str, Any],
) -> str:
    """Update the manifest after an incremental update, merging user files into the record."""

    manifest = load_manifest(project_dir)
    old_files: Dict[str, str] = {}
    if manifest:
        old_files = manifest.get("files", {})

    new_files: Dict[str, str] = {}
    for rel_path, content in sorted(new_render.items()):
        new_files[rel_path] = _hash_content(content)

    for rel_path in classifications.get("user_only", []):
        if rel_path not in new_files:
            target = Path(project_dir) / rel_path
            if target.exists():
                new_files[rel_path] = _hash_content(target.read_text(encoding="utf-8"))

    manifest_data = {
        "generated_at": datetime.now().isoformat(),
        "template_name": template_name,
        "template_version": template_version,
        "variables": variables,
        "files": new_files,
    }

    manifest_path = Path(project_dir) / MANIFEST_FILENAME
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest_data, f, indent=2, ensure_ascii=False)

    return str(manifest_path)